[build]
target = "riscv32em-unknown-none-elf"

[target.riscv32em-unknown-none-elf]
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-arg=--emit-relocs",
    "-C", "link-arg=--no-gc-sections",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.release]
strip = false
